### PR TITLE
rebalance construction times - construction is impractical due to the…

### PR DESCRIPTION
**Pull request by Nightcaper**
… time taken on the battlefield. Change made at request of Theel, feel free to look over and modify any changes you see fit to modify.

### CODE REVIEW

**Comment by AndrewTheel** [comment]
Make sure to assign labels, milestone, and assignee's to everything.  Looks good, I'd say this will be a big change as it effectively cuts the time required to build things by half.  Giving players who construct, less vulnerable time, this will also put more pressure on the supply system.  So its less about building up things and more about having the supply to place them.

**Comment by Nightcaper** [comment]
Thank you for the feedback. It seems I lack the permissions to assign labels to my PRs, assign others and such. I will make sure to do this when the system allows me to do so for my future PRs.

**Comment by cmbasnett** [comment]
This looks good, though you should probably to adjust the `Progress` levels on constructions where there are intermediate `Stages` as well (e.g. sandbags).

**Comment by Nightcaper** [comment]
Thanks for the feedback! Adjustments have been made to accommodate constructions with multiple stages.

**Pull request merged**
