### PR TITLE
Removed ammo resupply ability for lmg carriers.

### PR DESCRIPTION
**Pull request by randomguy3174**

### CODE REVIEW

**Comment by cmbasnett** [comment]
Doesn't this also have to apply to German FG42 gunners as well?

**Comment by GarlicAAZ** [comment]
> Doesn't this also have to apply to German FG42 gunners as well?

i think fg42 is usually given to commanders who have other options like mp40

**Comment by randomguy3174** [comment]
> Doesn't this also have to apply to German FG42 gunners as well?

It's hard to say for sure, since there's no specified fg42 carriers. 
Roles that uses fg42 by default is `DH_FJ45SquadLeader` and `DH_FJFireteamLeader`.
On per map basis weapon can be given for assault role(bhead).
Since all this roles have other weapons as choice i'm not sure if roles should be denied in carring of additional ammo.

**Comment by X2T5** [comment]
> i think fg42 is usually given to commanders who have other options like mp40

On the map: "DH-Les_Champs_de_Losque_Advance" for example you can find the FG42 for the "Rifleman" class.

DH-Les_Champs_de_Losque_Advance

**Comment by GDrukenmiller** [comment]
Probably what should happen with the FG42 situation is just remove the ability for it to be resupplied. It was more a hybrid weapon than the BAR or Bren and I don't think other soldiers would have been carrying spare mags for it (and it only gets weirder when you magically give another FG42 user a mag, while not losing any of your own).

**Comment by X2T5** [comment]
I absolutely agree with GDrukenmiller

**Review by cmbasnett — APPROVED** [review]

**Comment by cmbasnett** [comment]
Done, I have also removed the ability to resupply an FG42 on another branch that will be merged to main soon.

**Pull request merged**
